spring:
  application:
    name: stock-service

server:
  port: 8304

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8087/eureka/
    instance:
      hostname: localhost